spring:
  application:
    name: SpringBootTemplate

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  profiles:
    active: local  # 운영 환경 배포 시 prod로 변경

  # JSP ViewResolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # Jackson JSON 직렬화 시 속성명 전략을 CAMEL_CASE로 설정
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

# MyBatis Path
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*Mapper.xml

# Slf4j Logging
logging:
  config: classpath:logback-spring.xml
  level:
    kr.co.jaehoon.springboottemplate: debug

# Server Port/Error
server:
  port: 8080
  error:
    include-exception: true  # whitelabel.enabled=true 시 적용
    include-stacktrace: always  # whitelabel.enabled=true 시 적용
    whitelabel:
      enabled: false

# 애플리케이션 버전 정보 (모바일 앱 요청 테스트용)
app:
  version: 1.0.0

# SpringBootTemplate 프로젝트의 Release 버전을 기록
springboot-template:
  release:
    version: 0.000.005
